menu:
  首页: /
  归档: /archives
  游记: /

widgets:
- search
- category
- archive
- tagcloud
- links

excerpt_link: Read More

weixin:
  qrcode:
  alt: "欢迎关注个人公众号"

fancybox: true

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

links:
  谷歌: www.google.com
  百度: www.baidu.com
